# Set theme
remote_theme: daviddarnes/garth

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jekyll-remote-theme

# Site settings
url: 'https://infinitedimensionalspace.github.io/'
baseurl: ''
title: 'Infinite Dimensional Space'
description: 'musings of a meandering mind'
permalink: /:year/:title/
logo: "https://infinitedimensionalspace.github.io/favicon.ico"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Collections
collections:
  posts:
    title: 'Infinite Dimensional Space'
    output: true
    description: "musings of a meandering mind"
